### PR TITLE
save bilibili_history with json

### PR DESCRIPTION
**Pull request by zjgcjy**
fix https://github.com/yihong0618/GitHubPoster/issues/61

### CODE REVIEW

**Comment by yihong0618** [comment]
Thanks
Can you fix the lint?

**Comment by zjgcjy** [comment]
I don't know what's go wrong. flake8? I didn't use it. https://github.com/yihong0618/GitHubPoster/actions/runs/3195512610/jobs/5216660597#step:7:175

**Comment by yihong0618** [comment]
black and isort 
you can find the command in README

**Comment by yihong0618** [comment]
Will take a look tonight(^-^)

**Comment by yihong0618** [comment]
@zjgcjy drop `.gitignore` the `IN_FOLDER` for user easy to use `GitHub Actions`

**Comment by yihong0618** [comment]
Great thanks.

**Pull request merged**
