### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by deanwong**
### build
```
docker build -t github_poster .
```

### run

```
docker run --rm -v $(pwd)/OUT_FOLDER:/app/OUT_FOLDER github_poster duolingo --duolingo_user_name xxxxx --duolingo_password yyyyy --me whoami
```

The arguments after image_name (here is github_poster) will pass to python scripts directly.

### CODE REVIEW

**Comment by yihong0618** [comment]
LGTM

**Review by j178 — APPROVED** [review]
👍🏻

**Comment by yihong0618** [comment]
感谢

**Comment by bolechen** [comment]
macOs 13.0 下报错如下，请问是什么原因？

```
#10 34.09   Building wheel for cchardet (setup.py): started
#10 34.19   Building wheel for cchardet (setup.py): finished with status 'error'
#10 34.19   ERROR: Command errored out with exit status 1:
#10 34.19    command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_2lacp44/cchardet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_2lacp44/cchardet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xwe3oce9
#10 34.19        cwd: /tmp/pip-install-_2lacp44/cchardet/
#10 34.19   Complete output (20 lines):
#10 34.19   running bdist_wheel
#10 34.19   running build
#10 34.19   running build_py
#10 34.19   creating build
#10 34.19   creating build/lib.linux-aarch64-3.8
#10 34.19   creating build/lib.linux-aarch64-3.8/cchardet
#10 34.19   copying src/cchardet/version.py -> build/lib.linux-aarch64-3.8/cchardet
#10 34.19   copying src/cchardet/__init__.py -> build/lib.linux-aarch64-3.8/cchardet
#10 34.19   running build_ext
#10 34.19   building 'cchardet._cchardet' extension
#10 34.19   creating build/temp.linux-aarch64-3.8
#10 34.19   creating build/temp.linux-aarch64-3.8/src
#10 34.19   creating build/temp.linux-aarch64-3.8/src/cchardet
#10 34.19   creating build/temp.linux-aarch64-3.8/src/ext
#10 34.19   creating build/temp.linux-aarch64-3.8/src/ext/uchardet
#10 34.19   creating build/temp.linux-aarch64-3.8/src/ext/uchardet/src
#10 34.19   creating build/temp.linux-aarch64-3.8/src/ext/uchardet/src/LangModels
#10 34.19   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ext/uchardet/src -I/usr/local/include/python3.8 -c src/cchardet/_cchardet.cpp -o build/temp.linux-aarch64-3.8/src/cchardet/_cchardet.o
#10 34.19   unable to execute 'gcc': No such file or directory
#10 34.19   error: command 'gcc' failed with exit status 1
#10 34.19   ----------------------------------------
#10 34.19   ERROR: Failed building wheel for cchardet
#10 34.19   Running setup.py clean for cchardet
#10 34.28   Building wheel for googletransx (setup.py): started
#10 34.40   Building wheel for googletransx (setup.py): finished with status 'done'
#10 34.40   Created wheel for googletransx: filename=googletransx-2.4.2-py3-none-any.whl size=15971 sha256=9a1893c858cea37f95b37cfe4999a637291e97f5430c3b4fabacf7b2c581211a
#10 34.40   Stored in directory: /root/.cache/pip/wheels/6a/54/98/96b62f08dd73eca3147e36b5099d77c3f8fedc5472bb488167
#10 34.40 Successfully built pendulum twint-fork garminconnect gpxpy sdf-fork googletransx
#10 34.40 Failed to build cchardet
#10 34.64 Installing collected packages: urllib3, certifi, idna, charset-normalizer, requests, svgwrite, six, python-dateutil, pytzdata, pendulum, colour, attrs, async-timeout, multidict, yarl, frozenlist, aiosignal, aiohttp, pycparser, cffi, pycares, aiodns, soupsieve, beautifulsoup4, cchardet, dataclasses, elastic-transport, elasticsearch, pysocks, numpy, pytz, pandas, python-socks, aiohttp-socks, schedule, geographiclib, geopy, zipp, importlib-resources, fake-useragent, googletransx, twint-fork, requests-toolbelt, pyparsing, cloudscraper, garminconnect, gpxpy, pint, arrow, stravalib, pynacl, pyjwt, wrapt, deprecated, PyGithub, packaging, cycler, kiwisolver, Pillow, fonttools, contourpy, matplotlib, pygments, typing-extensions, commonmark, rich, meshio, PyWavelets, networkx, tifffile, imageio, scipy, scikit-image, sdf-fork, github-poster
#10 35.40     Running setup.py install for cchardet: started
#10 35.49     Running setup.py install for cchardet: finished with status 'error'
#10 35.49     ERROR: Command errored out with exit status 1:
#10 35.49      command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_2lacp44/cchardet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_2lacp44/cchardet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o3mwo2u3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cchardet
#10 35.49          cwd: /tmp/pip-install-_2lacp44/cchardet/
#10 35.49     Complete output (20 lines):
#10 35.49     running install
#10 35.49     running build
#10 35.49     running build_py
#10 35.49     creating build
#10 35.49     creating build/lib.linux-aarch64-3.8
#10 35.49     creating build/lib.linux-aarch64-3.8/cchardet
#10 35.49     copying src/cchardet/version.py -> build/lib.linux-aarch64-3.8/cchardet
#10 35.49     copying src/cchardet/__init__.py -> build/lib.linux-aarch64-3.8/cchardet
#10 35.49     running build_ext
#10 35.49     building 'cchardet._cchardet' extension
#10 35.49     creating build/temp.linux-aarch64-3.8
#10 35.49     creating build/temp.linux-aarch64-3.8/src
#10 35.49     creating build/temp.linux-aarch64-3.8/src/cchardet
#10 35.49     creating build/temp.linux-aarch64-3.8/src/ext
#10 35.49     creating build/temp.linux-aarch64-3.8/src/ext/uchardet
#10 35.49     creating build/temp.linux-aarch64-3.8/src/ext/uchardet/src
#10 35.49     creating build/temp.linux-aarch64-3.8/src/ext/uchardet/src/LangModels
#10 35.49     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ext/uchardet/src -I/usr/local/include/python3.8 -c src/cchardet/_cchardet.cpp -o build/temp.linux-aarch64-3.8/src/cchardet/_cchardet.o
#10 35.49     unable to execute 'gcc': No such file or directory
#10 35.49     error: command 'gcc' failed with exit status 1
#10 35.49     ----------------------------------------
#10 35.49 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_2lacp44/cchardet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_2lacp44/cchardet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o3mwo2u3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cchardet Check the logs for full command output.
#10 35.50 WARNING: You are using pip version 20.1; however, version 22.3.1 is available.
#10 35.50 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1
```

**Pull request merged**
