### PR TITLE
feat: ChatGPTOfficial loader

### PR DESCRIPTION
**Pull request by ztxtxwd**

### CODE REVIEW

**Comment by yihong0618** [comment]
@ztxtxwd can you fix the lint?

**Comment by ztxtxwd** [comment]
> 

I agree, that makes sense.

**Comment by yihong0618** [comment]
can you do that ?
just rename mine to yours and use your method

**Comment by ztxtxwd** [comment]
> can you do that ? just rename mine to yours and use your method

 Yes, I can make the changes as you specified.

**Comment by yihong0618** [comment]
@ztxtxwd LGTM

can you resolve the conflict?

**Pull request closed without merging**
